import localFont from "next/font/local";
import "./globals.css";


const foundersGrotesk = localFont({
  src: "./fonts/FoundersGrotesk-Semibold.woff", 
  variable: "--font-founders-grotesk",
});
const NeueMontreal = localFont({
  src: "./fonts/NeueMontreal-Regular.woff", 
  variable: "--font-neue-montreal",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${NeueMontreal.variable} ${foundersGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
